# Generated by Django 3.0.3 on 2020-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecenter',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
