# Generated by Django 3.0.3 on 2020-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine_App', '0003_auto_20201219_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecenter',
            name='latitude',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinecenter',
            name='longitude',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinecenter',
            name='phone',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
